name: Dependency-Track SBOM
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom:
    runs-on: self-hosted

    steps:
      - name: Generate SBOM
        shell: powershell
        run: |
           npx @cyclonedx/cyclonedx-npm --output-file bom.json

      - name: Check generated files
        shell: powershell
        run: |
          Get-ChildItem

      - name: Show SBOM component count
        shell: powershell
        run: |
          $bom = Get-Content bom.json | ConvertFrom-Json
          Write-Host "SBOM Version: $($bom.specVersion)"
          Write-Host "Project Name: $($bom.metadata.component.name)"
          Write-Host "Component Count: $($bom.components.Count)"

      - name: Upload SBOM to Dependency-Track
        shell: powershell
        run: |
          $response = curl.exe `
            -X POST "${{ secrets.DTRACK_URL }}/api/v1/bom" `
            -H "X-Api-Key: ${{ secrets.DTRACK_API_KEY }}" `
            -F "project=${{ secrets.DTRACK_PROJECT_UUID }}" `
            -F "bom=@bom.json"

          Write-Host "Dependency-Track Response:"
          Write-Host $response
